# Site settings
title: Anne-Kathrin Kleine 
email: a.k.kleine@rug.nl
description: >
 This is my website. It will be filled with content over the course of the summer. Looking forward to exchanging with you :) 
baseurl: "/fastnotfurious" 
url: "localhost:4000"
twitter_username: AnKaKleine
github_username: fastnotfurious

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
